### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by andrewschalk** [JessicaTegner/PyTinyTeX#4]
When running the code 'pytinytex.download_tinytex()', an error is thrown.

File "d:\ProgrammingProjects\WebScraping\NiceTabs.pyw", line 28, in \<module\>
pytinytex.download_tinytex(download_folder='./folder/')
File "D:\ProgrammingProjects\WebScraping\venv\lib\site-packages\pytinytex\tinytex_download.py", line 24, in download_tinytex
tinytex_urls, _ = _get_tinytex_urls(version, variation)
File "D:\ProgrammingProjects\WebScraping\venv\lib\site-packages\pytinytex\tinytex_download.py", line 80, in _get_tinytex_urls
version = tinytex_urls_list[0].split('/')[5]
IndexError: list index out of range

**Comment by JessicaTegner** [comment]
Hi @andrewschalk 

Can you tell me which version of PyTinyTeX you have installed?

Reason why I'm asking is because the line numbers in the stacktrace doesn't seem to match up with the code.

**Comment by andrewschalk** [comment]
Sorry, should have included it. I'm running 0.3.2. As far as I can tell, that's the only version I can get through pip?

**Comment by JessicaTegner** [comment]
can you let me know if the latest development snapshot works for you?

**Comment by andrewschalk** [comment]
I uninstalled the last version and ran `pip install git+https://github.com/JessicaTegner/PyTinyTeX` to install the current github version. The issue seems resolved in the current version, thanks for your help.
